### ISSUE TITLE
Illegal quoting error since v1.3.5 on windows server 2008R2 boxes

### ISSUE THREAD

**Issue by Annih** [WinRb/WinRM#159]
Hello,

After upgrade from winrm 1.3.4 to 1.3.5, our CI is facing Illegal quoting in line 1 error in test kitchen every time we try to converge a windows box.

Here is a stacktrace reproduced on my local windows workstation:

>D      ------Exception-------
>D      Class: Kitchen::ActionFailed
>D      Message: `Failed to complete #converge action: [Illegal quoting in line 1.]`
>D      ---Nested Exception---
>D      Class: CSV::MalformedCSVError
>D      Message: Illegal quoting in line 1.
>D      ------Backtrace-------
>D      C:/ruby/2.2.0/csv.rb:1874:in \`block (2 levels) in shift'
>D      C:/ruby/2.2.0/csv.rb:1836:in \`each'
>D      C:/ruby/2.2.0/csv.rb:1836:in \`block in shift'
>D      C:/ruby/2.2.0/csv.rb:1796:in \`loop'
>D      C:/ruby/2.2.0/csv.rb:1796:in \`shift'
>D      C:/ruby/2.2.0/csv.rb:1738:in \`each'
>D      C:/ruby/2.2.0/csv.rb:1752:in \`to_a'
>D      C:/ruby/2.2.0/csv.rb:1752:in \`read'
>D      C:/ruby/2.2.0/csv.rb:1298:in \`parse'
>D      C:/ruby/gems/2.2.0/gems/winrm-transport-1.0.3.dev/lib/winrm/transport/file_transporter.rb:391:in \`parse_response'
>D      C:/ruby/gems/2.2.0/gems/winrm-transport-1.0.3.dev/lib/winrm/transport/file_transporter.rb:184:in \`check_files'
>D      C:/ruby/gems/2.2.0/gems/winrm-transport-1.0.3.dev/lib/winrm/transport/file_transporter.rb:90:in \`block in upload'
>D      C:/ruby/2.2.0/benchmark.rb:288:in \`measure'
>D      C:/ruby/gems/2.2.0/gems/winrm-transport-1.0.3.dev/lib/winrm/transport/file_transporter.rb:87:in \`upload'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/transport/winrm.rb:118:in \`upload'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:68:in \`block in call'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/transport/base.rb:79:in \`initialize'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/transport/winrm.rb:423:in \`new'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/transport/winrm.rb:423:in \`create_new_connection'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/transport/winrm.rb:62:in \`connection'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:64:in \`call'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in \`block in converge_action'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in \`call'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in \`synchronize_or_call'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in \`block in action'
>D      C:/ruby/2.2.0/benchmark.rb:288:in \`measure'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in \`action'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in \`converge_action'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in \`block in transition_to'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in \`each'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in \`transition_to'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:138:in \`converge'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in \`public_send'
>D      C:/ruby/gems/2.2.0/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in \`block (2 levels) in run_action'
>D      C:/ruby/gems/2.2.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in \`call'
>D      C:/ruby/gems/2.2.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in \`block in create_with_logging_context'
>D      ----------------------

**Comment by mwrock** [comment]
what version of windows are you converging?

**Comment by Annih** [comment]
I tried on 2008R2 for sure, I can verify with a 2012R2.

**Comment by Annih** [comment]
Yes it's working on windows Server 2012 R2

**Comment by mwrock** [comment]
ok. interesting. I did test basic functionality on 2k8r2 but not via test kitchen. I can take a closer look over the next few days.

**Comment by mwrock** [comment]
looks like 2k8r2 is including the BOM in the output which is upsetting the CSV parser used in test-kitchen's winrm-transport gem. We should strip that off. Will find the best place to do that and have a fix soon.

**Comment by Annih** [comment]
Nice if you found the root cause of this issue :)
It's not urgent at all for me, I just moved to 2012R2 boxes.

**Comment by mwrock** [comment]
Hey then maybe this was a "blessing in disguise" :) I added a PR that fixes this. I'll release it in the next few days to let another pair of eyes review unless fires start elsewhere.

Thanks a bunch for reporting!

**Comment by b-dean** [comment]
@mwrock, This is broken again on 1.7.0 and 1.7.1. I suspect that this changeset is to blame 1615f8c8a2f876118fadf007ced04b3e38d4e4d6

**Comment by mwrock** [comment]
Well that was one of the intermediary commits before the final merge. It does look like the BOM is still getting zapped which was the fix in November. Could you provide the error and stack trace? Also the version of windows you are connecting to? Finally just curious if this is a Test-Kitchen scenario. Thanks!

**Comment by b-dean** [comment]
Windows 2k8r2, and this is with test-kitchen. Here's a stack:

```
I, [2016-02-24T16:29:56.747463 #7371]  INFO -- Kitchen: -----> Starting Kitchen (v1.4.2)
I, [2016-02-24T16:29:58.442011 #7371]  INFO -- Kitchen: -----> Cleaning up any prior instances of <default-windows-server2008R2>
I, [2016-02-24T16:29:58.442757 #7371]  INFO -- Kitchen: -----> Destroying <default-windows-server2008R2>...
I, [2016-02-24T16:29:58.443615 #7371]  INFO -- Kitchen: -----> Testing <default-windows-server2008R2>
I, [2016-02-24T16:29:58.443680 #7371]  INFO -- Kitchen: -----> Creating <default-windows-server2008R2>...
I, [2016-02-24T16:35:24.416777 #7371]  INFO -- Kitchen: -----> Converging <default-windows-server2008R2>...
E, [2016-02-24T16:36:35.830982 #7371] ERROR -- Kitchen: ------Exception-------
E, [2016-02-24T16:36:35.831051 #7371] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-02-24T16:36:35.831095 #7371] ERROR -- Kitchen: Message: Failed to complete #converge action: [Illegal quoting in line 1.]
E, [2016-02-24T16:36:35.831133 #7371] ERROR -- Kitchen: ---Nested Exception---
E, [2016-02-24T16:36:35.831170 #7371] ERROR -- Kitchen: Class: CSV::MalformedCSVError
E, [2016-02-24T16:36:35.831206 #7371] ERROR -- Kitchen: Message: Illegal quoting in line 1.
E, [2016-02-24T16:36:35.831242 #7371] ERROR -- Kitchen: ------Backtrace-------
E, [2016-02-24T16:36:35.831278 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1857:in `block (2 levels) in shift'
E, [2016-02-24T16:36:35.831315 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1819:in `each'
E, [2016-02-24T16:36:35.831351 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1819:in `block in shift'
E, [2016-02-24T16:36:35.831387 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1779:in `loop'
E, [2016-02-24T16:36:35.831423 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1779:in `shift'
E, [2016-02-24T16:36:35.831459 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1721:in `each'
E, [2016-02-24T16:36:35.831496 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1735:in `to_a'
E, [2016-02-24T16:36:35.831533 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1735:in `read'
E, [2016-02-24T16:36:35.831569 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1293:in `parse'
E, [2016-02-24T16:36:35.831605 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-transport-1.0.3/lib/winrm/transport/file_transporter.rb:391:in `parse_response'
E, [2016-02-24T16:36:35.831642 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-transport-1.0.3/lib/winrm/transport/file_transporter.rb:184:in `check_files'
E, [2016-02-24T16:36:35.831678 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-transport-1.0.3/lib/winrm/transport/file_transporter.rb:90:in `block in upload'
E, [2016-02-24T16:36:35.831714 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-24T16:36:35.831750 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-transport-1.0.3/lib/winrm/transport/file_transporter.rb:87:in `upload'
E, [2016-02-24T16:36:35.831787 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/transport/winrm.rb:118:in `upload'
E, [2016-02-24T16:36:35.831823 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:68:in `block in call'
E, [2016-02-24T16:36:35.831860 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/transport/winrm.rb:468:in `reuse_connection'
E, [2016-02-24T16:36:35.831906 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/transport/winrm.rb:60:in `connection'
E, [2016-02-24T16:36:35.831945 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/provisioner/base.rb:64:in `call'
E, [2016-02-24T16:36:35.831981 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:366:in `block in converge_action'
E, [2016-02-24T16:36:35.832017 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `call'
E, [2016-02-24T16:36:35.832053 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2016-02-24T16:36:35.832088 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:453:in `block in action'
E, [2016-02-24T16:36:35.832123 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-24T16:36:35.832158 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:452:in `action'
E, [2016-02-24T16:36:35.832194 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:362:in `converge_action'
E, [2016-02-24T16:36:35.832229 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2016-02-24T16:36:35.832264 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `each'
E, [2016-02-24T16:36:35.832300 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:340:in `transition_to'
E, [2016-02-24T16:36:35.832335 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:160:in `verify'
E, [2016-02-24T16:36:35.832371 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:189:in `block in test'
E, [2016-02-24T16:36:35.832406 #7371] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-24T16:36:35.832441 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/instance.rb:185:in `test'
E, [2016-02-24T16:36:35.832478 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `public_send'
E, [2016-02-24T16:36:35.832513 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/test-kitchen-1.4.2/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2016-02-24T16:36:35.832549 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
E, [2016-02-24T16:36:35.832584 #7371] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'
E, [2016-02-24T16:36:35.832627 #7371] ERROR -- Kitchen: ----------------------
```

**Comment by mwrock** [comment]
I see what I'm certain is the problem, 1.7.0's "fix" used single quotes around the BOM replacement instead of double. We obviously need a unit test around this. I'll get a fix in tonight. In the meantime, you may be able to work around this by using test-kitchen 1.5.0 which still uses the winrm-s monkey patch (going away in 1.6.0) that will have the winrm 1.6 encoding behavior.

Thanks so much for reporting this!

**Comment by sneal** [comment]
@mwrock See:
- https://github.com/WinRb/WinRM/blob/winrm-v2/lib/winrm/wsmv/command_output_decoder.rb
- https://github.com/WinRb/WinRM/blob/winrm-v2/tests/spec/wsmv/command_output_decoder_spec.rb

**Comment by b-dean** [comment]
I tried the same cookbook w/ the newer test-kitchen that uses winrm-fs and it has similar issues

Gemfile

```ruby
source 'https://rubygems.org'

gem 'test-kitchen', github: 'test-kitchen/test-kitchen'
gem 'kitchen-vagrant'
gem 'winrm-fs'
gem 'berkshelf'
```

kitchen.log
```
I, [2016-02-25T11:52:45.691390 #20065]  INFO -- Kitchen: -----> Starting Kitchen (v1.5.0)
I, [2016-02-25T11:52:46.953376 #20065]  INFO -- Kitchen: -----> Cleaning up any prior instances of <default-windows-server2008R2>
I, [2016-02-25T11:52:46.953684 #20065]  INFO -- Kitchen: -----> Destroying <default-windows-server2008R2>...
I, [2016-02-25T11:52:46.954899 #20065]  INFO -- Kitchen: -----> Testing <default-windows-server2008R2>
I, [2016-02-25T11:52:46.955072 #20065]  INFO -- Kitchen: -----> Creating <default-windows-server2008R2>...
I, [2016-02-25T11:58:09.209208 #20065]  INFO -- Kitchen: -----> Converging <default-windows-server2008R2>...
E, [2016-02-25T11:58:15.968820 #20065] ERROR -- Kitchen: ------Exception-------
E, [2016-02-25T11:58:15.968895 #20065] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2016-02-25T11:58:15.968938 #20065] ERROR -- Kitchen: Message: Failed to complete #converge action: [Illegal quoting in line 1.]
E, [2016-02-25T11:58:15.968978 #20065] ERROR -- Kitchen: ---Nested Exception---
E, [2016-02-25T11:58:15.969015 #20065] ERROR -- Kitchen: Class: CSV::MalformedCSVError
E, [2016-02-25T11:58:15.969052 #20065] ERROR -- Kitchen: Message: Illegal quoting in line 1.
E, [2016-02-25T11:58:15.969089 #20065] ERROR -- Kitchen: ------Backtrace-------
E, [2016-02-25T11:58:15.969125 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1857:in `block (2 levels) in shift'
E, [2016-02-25T11:58:15.969162 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1819:in `each'
E, [2016-02-25T11:58:15.969200 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1819:in `block in shift'
E, [2016-02-25T11:58:15.969237 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1779:in `loop'
E, [2016-02-25T11:58:15.969274 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1779:in `shift'
E, [2016-02-25T11:58:15.969311 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1721:in `each'
E, [2016-02-25T11:58:15.969348 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1735:in `to_a'
E, [2016-02-25T11:58:15.969385 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1735:in `read'
E, [2016-02-25T11:58:15.969422 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/csv.rb:1293:in `parse'
E, [2016-02-25T11:58:15.969459 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-fs-0.3.1/lib/winrm-fs/core/file_transporter.rb:381:in `parse_response'
E, [2016-02-25T11:58:15.969496 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-fs-0.3.1/lib/winrm-fs/core/file_transporter.rb:192:in `check_files'
E, [2016-02-25T11:58:15.969533 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-fs-0.3.1/lib/winrm-fs/core/file_transporter.rb:80:in `block in upload'
E, [2016-02-25T11:58:15.969570 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-25T11:58:15.969637 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/winrm-fs-0.3.1/lib/winrm-fs/core/file_transporter.rb:78:in `upload'
E, [2016-02-25T11:58:15.969677 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/transport/winrm.rb:129:in `upload'
E, [2016-02-25T11:58:15.969716 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/transport/winrm.rb:350:in `run_from_file_command'
E, [2016-02-25T11:58:15.969753 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/transport/winrm.rb:99:in `execute'
E, [2016-02-25T11:58:15.969802 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/provisioner/base.rb:67:in `block in call'
E, [2016-02-25T11:58:15.969842 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/transport/winrm.rb:474:in `reuse_connection'
E, [2016-02-25T11:58:15.969879 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/transport/winrm.rb:71:in `connection'
E, [2016-02-25T11:58:15.969915 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/provisioner/base.rb:66:in `call'
E, [2016-02-25T11:58:15.969952 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:373:in `block in converge_action'
E, [2016-02-25T11:58:15.969989 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:513:in `call'
E, [2016-02-25T11:58:15.970025 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:513:in `synchronize_or_call'
E, [2016-02-25T11:58:15.970061 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:478:in `block in action'
E, [2016-02-25T11:58:15.970097 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-25T11:58:15.970133 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:477:in `action'
E, [2016-02-25T11:58:15.970170 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:369:in `converge_action'
E, [2016-02-25T11:58:15.970206 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:348:in `block in transition_to'
E, [2016-02-25T11:58:15.970242 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:347:in `each'
E, [2016-02-25T11:58:15.970279 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:347:in `transition_to'
E, [2016-02-25T11:58:15.970315 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:160:in `verify'
E, [2016-02-25T11:58:15.970351 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:189:in `block in test'
E, [2016-02-25T11:58:15.970418 #20065] ERROR -- Kitchen: /home/ben/.rvm/rubies/ruby-2.1.8/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-02-25T11:58:15.970469 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/instance.rb:185:in `test'
E, [2016-02-25T11:58:15.970506 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/command.rb:176:in `public_send'
E, [2016-02-25T11:58:15.970560 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/bundler/gems/test-kitchen-e934595c24d9/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2016-02-25T11:58:15.970630 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `call'
E, [2016-02-25T11:58:15.970669 #20065] ERROR -- Kitchen: /home/ben/.rvm/gems/ruby-2.1.8@cookbook-foo/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'
E, [2016-02-25T11:58:15.970706 #20065] ERROR -- Kitchen: ----------------------
```

**Comment by mwrock** [comment]
yep. Has to be 1.5.0.  Master will have the same issue.

**Comment by b-dean** [comment]
I tried 1.5 first it had the same problem. I switched to master when I saw your stuff on master to make kitchen use winrm-fs

**Comment by mwrock** [comment]
hmm. ok. I had thought the winrm-s monkey patch would have protected against the 1.7 regression. Well should have a true fix here soon.

**Comment by b-dean** [comment]
If I add this to my Gemfile, it seems to work (with either winrm-fs or winrm-transport, and the appropriate kitchen version) 

```ruby
gem 'winrm', github: 'WinRb/WinRM', branch: 'bombom'
```

**Comment by mwrock** [comment]
yeah just got a successful 2k8r2 run myself on that. will release now.

**Comment by mwrock** [comment]
releasing on the bus is the best :)

**Comment by mwrock** [comment]
1.7.2 now on rubygems

**Comment by b-dean** [comment]
thanks @mwrock :smile:
