### ISSUE TITLE
WinRM hangs when using an IO.FileStream within script

### ISSUE THREAD

**Issue by djberg96** [WinRb/WinRM#162]
Hi,

ruby 2.2.3p173
winrm 1.3.6
OSX - El Capitain

I'm hitting an issue where a script that creates an IO.Filestream object never returns, and I'm not sure why. I'm definitely closing it.

Any ideas?

Below is the sample ruby script and powershell script:

```
# compression_test.rb
require 'winrm'

endpoint = 'http://1.2.3.4' # My endpoint
username = 'some_user
password = 'xxxxxx'

psscript  = 'compression.ps1'

winrm = WinRM::WinRMWebService.new(
  endpoint,
  :ssl,
  :user         => username,
  :pass         => password,
  :disable_sspi => true
)

winrm.set_timeout(1800)

result = winrm.run_powershell_script(IO.read(psscript))

p result.stdout
```

```
#  compression.ps1
$file = 'temp.json'
Get-Service -Name W32Time | ConvertTo-Json -Depth 4 | Out-File $file

# If you comment out these two lines, then it works
$input = New-Object System.IO.FileStream $file, ([IO.FileMode]::Open), ([IO.FileAccess]::Read), ([IO.FileShare]::Read)
$input.Dispose() # Also tried Close()

Get-Content $file -Raw
```

After it hangs for a bit, I hit ctrl-c and get this output:

```
>ruby compression_test.rb
^C/Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `gets': Interrupt
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `block in parse_header'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `call'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:124:in `timeout'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:855:in `read_header'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:662:in `get_header'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1247:in `do_get_header'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1194:in `do_get_block'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:725:in `post'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/http/transport.rb:47:in `send_request'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:432:in `send_message'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:417:in `send_get_output_message'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:231:in `get_command_output'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:303:in `block (2 levels) in run_cmd'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:174:in `run_command'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:302:in `block in run_cmd'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:131:in `open_shell'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:301:in `run_cmd'
	from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/winrm-1.3.6/lib/winrm/winrm_service.rb:319:in `run_powershell_script'
	from compression_test.rb:22:in `<main>'
```

**Comment by mwrock** [comment]
The issue is the use of the `$input` variable. `$input` is an "automatic" variable in powershell used to enumerate pipeline input. Your script is hanging waiting for input on the pipeline. You can work around this by simply using another variable like $in, $json, etc.

**Comment by djberg96** [comment]
Oh, silly me. Thank you very much.
