### ISSUE TITLE
HTTPClient ConnectTimeoutError during command

### ISSUE THREAD

**Issue by marceloneil** [WinRb/WinRM#274]
Although I am using [winrm-elevated](https://github.com/WinRb/winrm-elevated), I've had similar issues with the `cmd` and `powershell` shells. In the middle of long commands (ie. bleachbit), I get a `ConnectTimeoutError`

```
...
Delete 2.5kB C:\Windows\SoftwareDistribution\Download\5357628bb82658534f104e49df1ff3a4\wow64_microsoft-windows-kernelbase.resources_31bf3856ad364e35_6.1.7601.22125_tr-tr_6f4063c451977fb4.manifest
Delete 2.5kB C:\Windows\SoftwareDistribution\Download\5357628bb82658534f104e49df1ff3a4\wow64_microsoft-windows-kernelbase.resources_31bf3856ad364e35_6.1.7601.22125_uk-ua_0b20466b48c8a600.manifest
Delete 2.5kB C:\Windows\SoftwareDistribution\Download\5357628bb82658534f104e49df1ff3a4\wow64_microsoft-windows-kernelbase.resources_31bf3856ad364e35_6.1.7601.22125_zh-cn_409d81c201cf51d3.manifest
Delete 2.5kB C:\Windows\SoftwareDistribution\Download\5357628bb82658534f104e49df1ff3a4\wow64_microsoft-windows-kernelbase.resources_31bf3856ad364e35_6.1.7601.22125_zh-tw_4499bf17ff402e43.manifest
Delete 2.7kB C:\Windows\SoftwareDistribution\Download\5357628bb82658534f104e49df1ff3a4\wow64_microsoft-windows-
/home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `initialize': execution expired (HTTPClient::ConnectTimeoutError)
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `new'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `create_socket'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:755:in `block in connect'
        from /usr/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
        from /home/marcel/.gem/ruby/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
        from /home/marcel/.gem/ruby/2.4.0/gems/winrm-2.2.3/lib/winrm/http/transport.rb:177:in `send_request'
        from /home/marcel/.gem/ruby/2.4.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:156:in `cleanup_command'
        from /home/marcel/.gem/ruby/2.4.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:138:in `ensure in with_command_shell'
        from /home/marcel/.gem/ruby/2.4.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:138:in `with_command_shell'
        from /home/marcel/.gem/ruby/2.4.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:81:in `run'
        from /home/marcel/.gem/ruby/2.4.0/gems/winrm-elevated-1.1.0/lib/winrm/shells/elevated.rb:60:in `run'
        from update.rb:33:in `run'
        from update.rb:159:in `<main>'
```

And here is essentially what is happening in `update.rb`:
```
config = {
  endpoint: "http://127.0.0.1:5985/wsman",
  user: '<username>',
  password: '<password>',
  operation_timeout: 300
}
winrm = WinRM::Connection.new config
shell = winrm.shell :elevated
shell.run 'D:\bleachbit\bleachbit_console.exe --preset --clean' do |stdout, stderr|
  puts stdout
  if stderr
    puts stderr.red
  end
end
```

I am using the same shell to run multiple commands (including rebooting)
Any help is greatly appreciated!

**Comment by mwrock** [comment]
hmm. Could the node be rebooting while you are in the midst of trying to connect?
