### ISSUE TITLE
Powershell echo of higher unicode crashes PipelineOutput.extract_out_string

### ISSUE THREAD

**Issue by cork** [WinRb/WinRM#282]
```ruby
shell = conn.shell(:powershell)
shell.run("echo 🌓")
Traceback (most recent call last):
       16: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:65:in `read_response'
       15: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:119:in `read_streams'
       14: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:119:in `each'
       13: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:121:in `block in read_streams'
       12: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/wsmv/receive_response_reader.rb:66:in `block in read_response'
       11: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/receive_response_reader.rb:45:in `block in read_message'
       10: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/receive_response_reader.rb:63:in `block (2 levels) in read_output'
        9: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/powershell_output_decoder.rb:33:in `decode'
        8: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/powershell_output_decoder.rb:51:in `decode_pipeline_output'
        7: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/message_data/pipeline_output.rb:25:in `output'
        6: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/message_data/pipeline_output.rb:32:in `extract_out_string'
        5: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/message_data/pipeline_output.rb:32:in `map'
        4: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/message_data/pipeline_output.rb:35:in `block in extract_out_string'
        3: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/message_data/pipeline_output.rb:35:in `gsub'
        2: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/message_data/pipeline_output.rb:36:in `block (2 levels) in extract_out_string'
        1: from /tmp/test/.bundle/ruby/2.5.0/gems/winrm-2.2.3/lib/winrm/psrp/message_data/pipeline_output.rb:36:in `chr'
RangeError (55356 out of char range)
```

**Comment by pcai** [comment]
Closing this out — this was fixed the same day it was reported (the pipeline encoding now uses `pack('S*')`), and the fix has been on main ever since. Thanks for reporting!
