### ISSUE TITLE
can't alloc thread (ThreadError)

### ISSUE THREAD

**Issue by lmayorga1980** [WinRb/WinRM#345]
Using ruby `3.2.1` to run a test-kitchen verification against a Windows Server.

Is the new winrm with ruby 3.x support coming soon?

```
bundle exec kitchen converge                                                                                                        
-----> Starting Test Kitchen (v3.6.0)
-----> Converging <default-windows-2019>...
       Preparing files for transfer
       Preparing script
       No provisioner script file specified, skipping
       Transferring files to <default-windows-2019>
       Downloading files from <default-windows-2019>
       Finished converging <default-windows-2019> (0m1.05s).
-----> Test Kitchen is finished. (0m1.76s)
/Users/lcentinel/.rbenv/versions/3.3.0/bin/bundle: warning: Exception in finalizer #<Proc:0x0000000130f724a8 /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:33>
/Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/logging-2.4.0/lib/logging/diagnostic_context.rb:471:in `new': can't alloc thread (ThreadError)
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/logging-2.4.0/lib/logging/diagnostic_context.rb:471:in `create_with_logging_context'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/logging-2.4.0/lib/logging/diagnostic_context.rb:436:in `new'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/3.3.0/timeout.rb:98:in `create_timeout_thread'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/3.3.0/timeout.rb:131:in `block in ensure_timeout_thread_created'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/3.3.0/timeout.rb:129:in `synchronize'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/3.3.0/timeout.rb:129:in `ensure_timeout_thread_created'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/3.3.0/timeout.rb:178:in `timeout'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:515:in `query'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:176:in `send_request'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:42:in `close_shell'
	from /Users/lcentinel/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:33:in `block in finalize'
```

**Comment by pcai** [comment]
Closing this out — the finalizer ThreadError is fixed at the root by #354, which is on main and will ship with the next release. Thanks for reporting!
